name: Build CI

on:
  pull_request:
    types: [closed]

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Create Release Tag
        env:
          GITHUB_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ steps.package-version.outputs.current-version }}
        uses: release-drafter/release-drafter@v6
        with:
          tag: v${{ env.RELEASE_TAG }}
          name: v${{ env.RELEASE_TAG }}
          version: v${{ env.RELEASE_TAG }}
